apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jaegers.jaegertracing.io
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: jaeger-operator
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Jaeger instance's status
    name: Status
    type: string
  - JSONPath: .status.version
    description: Jaeger Version
    name: Version
    type: string
  group: jaegertracing.io
  names:
    kind: Jaeger
    listKind: JaegerList
    plural: jaegers
    singular: jaeger
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
