apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jaegers.jaegertracing.io
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: jaeger-operator
spec:
  group: jaegertracing.io
  names:
    kind: Jaeger
    listKind: JaegerList
    plural: jaegers
    singular: jaeger
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - jsonPath: .status.phase
          description: Jaeger instance's status
          name: Status
          type: string
        - jsonPath: .status.version
          description: Jaeger Version
          name: Version
          type: string
        - description: Jaeger deployment strategy
          jsonPath: .spec.strategy
          name: Strategy
          type: string
        - description: Jaeger storage type
          jsonPath: .spec.storage.type
          name: Storage
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      subresources:
        status: {}
