{{- if and .Values.networkPolicy.enabled .Values.query.networkPolicy.enabled .Values.query.networkPolicy.egressRules }}
{{- $extraVals := dict "Name" (include "jaeger.query.name" .) "Component" "query" "ComponentValues" .Values.query -}}
{{- $npVals := merge $extraVals . -}}
{{ include "jaeger.egress.networkPolicy" $npVals }}
{{- end }}
