name: Prepare K8s for Helm tests
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
      with:
        version: v3.16.4

    # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
    # yamllint (https://github.com/adrienverge/yamllint) which require Python
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: 3.9

    - name: Set up chart-testing
      uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

    - name: Create kind cluster
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0

    - name: Install kubectl
      uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v4.0.0
      with:
        version: 'v1.30.8'
      id: install

    - name: Set up cert-manager
      shell: bash
      run: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml --namespace ingress-nginx
        kubectl label node --all ingress-ready=true
        kubectl describe pod --selector=app.kubernetes.io/component=controller -n ingress-nginx
        kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=5m
        kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml

    - name: Set up cmctl
      shell: bash
      run: |
        curl -sSL -o cmctl.tar.gz https://github.com/cert-manager/cert-manager/releases/download/v1.6.1/cmctl-linux-amd64.tar.gz
        tar xzf cmctl.tar.gz
        sudo mv cmctl /usr/local/bin
        cmctl version

    - name: Check if cert-manager is up
      shell: bash
      run: |
        cmctl check api --wait=5m
