apiVersion: v1
description: jaeger-operator Helm chart for Kubernetes
name: jaeger-operator
version: 2.24.0
appVersion: 1.24.0
home: https://www.jaegertracing.io/
icon: https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg
sources:
  - https://github.com/jaegertracing/jaeger-operator
maintainers:
  - email: ctadeu@gmail.com
    name: cpanato
  - email: batazor111@gmail.com
    name: batazor
