{{- if .Values.certs.issuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ default "selfsigned-issuer" .Values.certs.issuer.name }}
  namespace: {{ include "jaeger-operator.namespace" . }}
spec:
  selfSigned: {}
{{- end }}
