{{- if .Values.jaeger.create }}
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: {{ include "jaeger-operator.fullname" . }}-jaeger
  namespace: {{ default .Values.jaeger.namespace (include "jaeger-operator.namespace" .) }}
{{- with .Values.jaeger.spec }}
spec:
{{ toYaml . | indent 2}}
{{- end }}
{{- end }}
